const ar = {
  footer: { channelTitle: "القرآن الكريم وتلاواته", channelDesc: "تابع القناة لمشاهدة تلاوات القرآن الكريم والمقاطع الإيمانية الجديدة.", visitChannel: "زيارة القناة على YouTube", siteTitle: "القرآن المجيد", siteDesc: "مصحف إلكتروني مجاني لقراءة القرآن الكريم والاستماع إلى التلاوات وتصفّح صفحات المصحف بسهولة على جميع الأجهزة.", siteMission: "نسأل الله أن يجعل هذا العمل نافعًا، وأن يكتب أجره لكل من قرأ واستمع ونشر الخير.", quranBasics: "الأساسيات القرآنية", siteServices: "خدمات الموقع", quranHome: "القرآن الكريم", surahs: "سور القرآن", verseSearch: "البحث في الآيات", quranPages: "صفحات القرآن", recitations: "تلاوات القرآن", mushafLibrary: "مكتبة المصاحف", live: "البث المباشر", calendar: "التقويم الإسلامي", noor: "مساعد نور", reader: "قارئ القرآن", about: "عن الموقع", install: "تثبيت التطبيق", dedication: "اللهم اجعل هذا الموقع صدقة جارية لنا ولوالدينا وأهل بيتنا وموتانا، واغفر لهم وارحمهم ووفّقنا لخدمة دينك.", charity: "القرآن المجيد — صدقة جارية، فلا تنسونا من صالح دعائكم", linksLabel: "روابط الفوتر", logoAlt: "شعار قناة القرآن الكريم وتلاواته" },
  live: { primary: "بث مباشر - قناة القرآن الكريم من مكة", backup: "بث مباشر - قناة القرآن الكريم (احتياطي)", title: "البث المباشر", subtitle: "قنوات القرآن الكريم والسنة النبوية", videoError: "تعذر تحميل البث المباشر. جرّب القناة الاحتياطية.", loading: "جاري تحميل البث...", connected: "متصل", quality: "جودة الاتصال: ممتاز", available: "القنوات المتاحة", radioPlayer: "مشغل الإذاعة المباشر", radioSubtitle: "استمع إلى إذاعات القرآن الكريم والبرامج الإسلامية", radioTitle: "إذاعة القرآن الكريم", radioTagline: "استمع للقرآن الكريم مباشرة", favorite: "إضافة إلى المفضلة", share: "مشاركة الإذاعة", noStations: "لا توجد إذاعات متاحة", connecting: "جاري الاتصال...", onAir: "● مباشر", ready: "جاهز للتشغيل", choose: "اختر إذاعة", radioError: "تعذر تشغيل هذه الإذاعة، جرّب إذاعة أخرى.", previous: "الإذاعة السابقة", next: "الإذاعة التالية", pause: "إيقاف مؤقت", play: "تشغيل", unmute: "تشغيل الصوت", mute: "كتم الصوت", volume: "مستوى الصوت", channelsLabel: "قنوات البث المباشر" },
};

const en = {
  footer: { channelTitle: "The Holy Quran and Its Recitations", channelDesc: "Follow the channel for Quran recitations and new faith-inspired videos.", visitChannel: "Visit the channel on YouTube", siteTitle: "Al-Quran Al-Majeed", siteDesc: "A free digital Quran for reading, listening to recitations, and browsing Mushaf pages easily on every device.", siteMission: "We ask Allah to make this work beneficial and reward everyone who reads, listens, and shares goodness.", quranBasics: "Quran Essentials", siteServices: "Site Services", quranHome: "The Holy Quran", surahs: "Quran Surahs", verseSearch: "Search Verses", quranPages: "Quran Pages", recitations: "Quran Recitations", mushafLibrary: "Mushaf Library", live: "Live Broadcast", calendar: "Islamic Calendar", noor: "Noor Assistant", reader: "Quran Reader", about: "About the Site", install: "Install the App", dedication: "O Allah, make this site an ongoing charity for us, our parents, families, and departed loved ones. Forgive them, have mercy on them, and help us serve Your religion.", charity: "Al-Quran Al-Majeed — an ongoing charity; remember us in your prayers", linksLabel: "Footer links", logoAlt: "The Holy Quran and Its Recitations channel logo" },
  live: { primary: "Live - Holy Quran Channel from Makkah", backup: "Live - Holy Quran Channel (Backup)", title: "Live Broadcast", subtitle: "Holy Quran and Prophetic Sunnah channels", videoError: "The live broadcast could not be loaded. Try the backup channel.", loading: "Loading broadcast...", connected: "Connected", quality: "Connection quality: Excellent", available: "Available Channels", radioPlayer: "Live Radio Player", radioSubtitle: "Listen to Quran radio stations and Islamic programs", radioTitle: "Holy Quran Radio", radioTagline: "Listen to the Holy Quran live", favorite: "Add to favorites", share: "Share radio", noStations: "No radio stations available", connecting: "Connecting...", onAir: "● Live", ready: "Ready to play", choose: "Choose a radio station", radioError: "This station could not be played. Try another station.", previous: "Previous station", next: "Next station", pause: "Pause", play: "Play", unmute: "Unmute", mute: "Mute", volume: "Volume", channelsLabel: "Live broadcast channels" },
};

export const footerLiveTranslations = {
  ar,
  en,
  de: {
    footer: { channelTitle: "Der Heilige Koran und seine Rezitationen", channelDesc: "Folgen Sie dem Kanal für Koranrezitationen und neue Glaubensvideos.", visitChannel: "Kanal auf YouTube besuchen", siteTitle: "Al-Quran Al-Majeed", siteDesc: "Ein kostenloser digitaler Koran zum Lesen, Anhören von Rezitationen und einfachen Durchblättern der Mushaf-Seiten auf allen Geräten.", siteMission: "Wir bitten Allah, dieses Werk nützlich zu machen und jeden zu belohnen, der liest, zuhört und Gutes verbreitet.", quranBasics: "Koran-Grundlagen", siteServices: "Website-Dienste", quranHome: "Der Heilige Koran", surahs: "Koransuren", verseSearch: "Verse durchsuchen", quranPages: "Koranseiten", recitations: "Koranrezitationen", mushafLibrary: "Mushaf-Bibliothek", live: "Live-Übertragung", calendar: "Islamischer Kalender", noor: "Noor-Assistent", reader: "Koranleser", about: "Über die Website", install: "App installieren", dedication: "O Allah, mache diese Website zu einer fortdauernden Wohltat für uns, unsere Eltern, Familien und Verstorbenen. Vergib ihnen, erbarme Dich ihrer und hilf uns, Deiner Religion zu dienen.", charity: "Al-Quran Al-Majeed — eine fortdauernde Wohltat; gedenkt unser in euren Gebeten", linksLabel: "Footer-Links", logoAlt: "Logo des Kanals Der Heilige Koran und seine Rezitationen" },
    live: { primary: "Live – Heiliger-Koran-Kanal aus Mekka", backup: "Live – Heiliger-Koran-Kanal (Ersatz)", title: "Live-Übertragung", subtitle: "Kanäle für den Heiligen Koran und die prophetische Sunna", videoError: "Die Live-Übertragung konnte nicht geladen werden. Versuchen Sie den Ersatzkanal.", loading: "Übertragung wird geladen...", connected: "Verbunden", quality: "Verbindungsqualität: Ausgezeichnet", available: "Verfügbare Kanäle", radioPlayer: "Live-Radioplayer", radioSubtitle: "Hören Sie Koranradios und islamische Programme", radioTitle: "Heiliger-Koran-Radio", radioTagline: "Den Heiligen Koran live hören", favorite: "Zu Favoriten hinzufügen", share: "Radio teilen", noStations: "Keine Radiosender verfügbar", connecting: "Verbindung wird hergestellt...", onAir: "● Live", ready: "Wiedergabebereit", choose: "Radiosender wählen", radioError: "Dieser Sender konnte nicht abgespielt werden. Versuchen Sie einen anderen.", previous: "Vorheriger Sender", next: "Nächster Sender", pause: "Pause", play: "Wiedergabe", unmute: "Ton einschalten", mute: "Stummschalten", volume: "Lautstärke", channelsLabel: "Live-Übertragungskanäle" },
  },
  es: {
    footer: { channelTitle: "El Sagrado Corán y sus recitaciones", channelDesc: "Sigue el canal para ver recitaciones del Corán y nuevos vídeos de fe.", visitChannel: "Visitar el canal en YouTube", siteTitle: "Al-Quran Al-Majeed", siteDesc: "Un Corán digital gratuito para leer, escuchar recitaciones y explorar fácilmente las páginas del Mushaf en cualquier dispositivo.", siteMission: "Pedimos a Alá que haga beneficiosa esta obra y recompense a todos los que leen, escuchan y difunden el bien.", quranBasics: "Fundamentos del Corán", siteServices: "Servicios del sitio", quranHome: "El Sagrado Corán", surahs: "Suras del Corán", verseSearch: "Buscar aleyas", quranPages: "Páginas del Corán", recitations: "Recitaciones del Corán", mushafLibrary: "Biblioteca de Mushaf", live: "Transmisión en vivo", calendar: "Calendario islámico", noor: "Asistente Noor", reader: "Lector del Corán", about: "Acerca del sitio", install: "Instalar la aplicación", dedication: "Oh Alá, haz de este sitio una caridad continua para nosotros, nuestros padres, familias y seres queridos fallecidos. Perdónalos, ten misericordia de ellos y ayúdanos a servir Tu religión.", charity: "Al-Quran Al-Majeed — una caridad continua; recuérdanos en tus oraciones", linksLabel: "Enlaces del pie de página", logoAlt: "Logotipo del canal El Sagrado Corán y sus recitaciones" },
    live: { primary: "En vivo - Canal del Sagrado Corán desde La Meca", backup: "En vivo - Canal del Sagrado Corán (reserva)", title: "Transmisión en vivo", subtitle: "Canales del Sagrado Corán y la Sunna profética", videoError: "No se pudo cargar la transmisión. Prueba el canal de reserva.", loading: "Cargando transmisión...", connected: "Conectado", quality: "Calidad de conexión: Excelente", available: "Canales disponibles", radioPlayer: "Reproductor de radio en vivo", radioSubtitle: "Escucha emisoras del Corán y programas islámicos", radioTitle: "Radio del Sagrado Corán", radioTagline: "Escucha el Sagrado Corán en vivo", favorite: "Añadir a favoritos", share: "Compartir radio", noStations: "No hay emisoras disponibles", connecting: "Conectando...", onAir: "● En vivo", ready: "Listo para reproducir", choose: "Elegir una emisora", radioError: "No se pudo reproducir esta emisora. Prueba otra.", previous: "Emisora anterior", next: "Emisora siguiente", pause: "Pausar", play: "Reproducir", unmute: "Activar sonido", mute: "Silenciar", volume: "Volumen", channelsLabel: "Canales de transmisión en vivo" },
  },
  fr: {
    footer: { channelTitle: "Le Saint Coran et ses récitations", channelDesc: "Suivez la chaîne pour découvrir des récitations du Coran et de nouvelles vidéos spirituelles.", visitChannel: "Visiter la chaîne sur YouTube", siteTitle: "Al-Quran Al-Majeed", siteDesc: "Un Coran numérique gratuit pour lire, écouter des récitations et parcourir facilement les pages du Mushaf sur tous les appareils.", siteMission: "Nous demandons à Allah de rendre cette œuvre utile et de récompenser tous ceux qui lisent, écoutent et partagent le bien.", quranBasics: "Fondamentaux du Coran", siteServices: "Services du site", quranHome: "Le Saint Coran", surahs: "Sourates du Coran", verseSearch: "Rechercher des versets", quranPages: "Pages du Coran", recitations: "Récitations du Coran", mushafLibrary: "Bibliothèque de Mushaf", live: "Diffusion en direct", calendar: "Calendrier islamique", noor: "Assistant Noor", reader: "Lecteur du Coran", about: "À propos du site", install: "Installer l’application", dedication: "Ô Allah, fais de ce site une aumône continue pour nous, nos parents, nos familles et nos défunts. Pardonne-leur, accorde-leur Ta miséricorde et aide-nous à servir Ta religion.", charity: "Al-Quran Al-Majeed — une aumône continue ; souvenez-vous de nous dans vos prières", linksLabel: "Liens du pied de page", logoAlt: "Logo de la chaîne Le Saint Coran et ses récitations" },
    live: { primary: "En direct - Chaîne du Saint Coran depuis La Mecque", backup: "En direct - Chaîne du Saint Coran (secours)", title: "Diffusion en direct", subtitle: "Chaînes du Saint Coran et de la Sunna prophétique", videoError: "Impossible de charger la diffusion. Essayez la chaîne de secours.", loading: "Chargement de la diffusion...", connected: "Connecté", quality: "Qualité de connexion : Excellente", available: "Chaînes disponibles", radioPlayer: "Lecteur radio en direct", radioSubtitle: "Écoutez les radios du Coran et les programmes islamiques", radioTitle: "Radio du Saint Coran", radioTagline: "Écoutez le Saint Coran en direct", favorite: "Ajouter aux favoris", share: "Partager la radio", noStations: "Aucune radio disponible", connecting: "Connexion...", onAir: "● En direct", ready: "Prêt à lire", choose: "Choisir une radio", radioError: "Impossible de lire cette radio. Essayez-en une autre.", previous: "Radio précédente", next: "Radio suivante", pause: "Pause", play: "Lecture", unmute: "Activer le son", mute: "Couper le son", volume: "Volume", channelsLabel: "Chaînes de diffusion en direct" },
  },
  hi: {
    footer: { channelTitle: "पवित्र कुरान और उसकी तिलावतें", channelDesc: "कुरान की तिलावत और नए ईमान प्रेरित वीडियो देखने के लिए चैनल को फ़ॉलो करें।", visitChannel: "YouTube पर चैनल देखें", siteTitle: "अल-कुरान अल-मजीद", siteDesc: "हर डिवाइस पर कुरान पढ़ने, तिलावत सुनने और मुसहफ़ के पन्ने आसानी से देखने के लिए निःशुल्क डिजिटल कुरान।", siteMission: "हम अल्लाह से दुआ करते हैं कि वह इस कार्य को लाभकारी बनाए और पढ़ने, सुनने तथा भलाई फैलाने वालों को सवाब दे।", quranBasics: "कुरान की मूल बातें", siteServices: "साइट सेवाएँ", quranHome: "पवित्र कुरान", surahs: "कुरान की सूरहें", verseSearch: "आयतें खोजें", quranPages: "कुरान के पन्ने", recitations: "कुरान की तिलावतें", mushafLibrary: "मुसहफ़ पुस्तकालय", live: "लाइव प्रसारण", calendar: "इस्लामी कैलेंडर", noor: "नूर सहायक", reader: "कुरान रीडर", about: "साइट के बारे में", install: "ऐप इंस्टॉल करें", dedication: "ऐ अल्लाह, इस साइट को हमारे, हमारे माता-पिता, परिवारों और दिवंगत प्रियजनों के लिए सदक़ा-ए-जारीया बना। उन्हें क्षमा कर, उन पर दया कर और हमें अपने दीन की सेवा में सहायता दे।", charity: "अल-कुरान अल-मजीद — सदक़ा-ए-जारीया; अपनी दुआओं में हमें याद रखें", linksLabel: "फ़ुटर लिंक", logoAlt: "पवित्र कुरान और उसकी तिलावतें चैनल का लोगो" },
    live: { primary: "लाइव - मक्का से पवित्र कुरान चैनल", backup: "लाइव - पवित्र कुरान चैनल (बैकअप)", title: "लाइव प्रसारण", subtitle: "पवित्र कुरान और पैग़ंबरी सुन्नत के चैनल", videoError: "लाइव प्रसारण लोड नहीं हुआ। बैकअप चैनल आज़माएँ।", loading: "प्रसारण लोड हो रहा है...", connected: "कनेक्टेड", quality: "कनेक्शन गुणवत्ता: उत्कृष्ट", available: "उपलब्ध चैनल", radioPlayer: "लाइव रेडियो प्लेयर", radioSubtitle: "कुरान रेडियो और इस्लामी कार्यक्रम सुनें", radioTitle: "पवित्र कुरान रेडियो", radioTagline: "पवित्र कुरान लाइव सुनें", favorite: "पसंदीदा में जोड़ें", share: "रेडियो साझा करें", noStations: "कोई रेडियो स्टेशन उपलब्ध नहीं", connecting: "कनेक्ट हो रहा है...", onAir: "● लाइव", ready: "चलाने के लिए तैयार", choose: "रेडियो चुनें", radioError: "यह रेडियो नहीं चल सका। दूसरा रेडियो आज़माएँ।", previous: "पिछला रेडियो", next: "अगला रेडियो", pause: "रोकें", play: "चलाएँ", unmute: "ध्वनि चालू करें", mute: "म्यूट करें", volume: "आवाज़", channelsLabel: "लाइव प्रसारण चैनल" },
  },
  id: {
    footer: { channelTitle: "Al-Quran Suci dan Tilawahnya", channelDesc: "Ikuti kanal untuk tilawah Al-Quran dan video keimanan terbaru.", visitChannel: "Kunjungi kanal di YouTube", siteTitle: "Al-Quran Al-Majeed", siteDesc: "Al-Quran digital gratis untuk membaca, mendengarkan tilawah, dan menjelajahi halaman Mushaf dengan mudah di semua perangkat.", siteMission: "Kami memohon kepada Allah agar karya ini bermanfaat dan memberi pahala kepada siapa pun yang membaca, mendengar, dan menyebarkan kebaikan.", quranBasics: "Dasar-dasar Al-Quran", siteServices: "Layanan Situs", quranHome: "Al-Quran Suci", surahs: "Surah Al-Quran", verseSearch: "Cari Ayat", quranPages: "Halaman Al-Quran", recitations: "Tilawah Al-Quran", mushafLibrary: "Perpustakaan Mushaf", live: "Siaran Langsung", calendar: "Kalender Islam", noor: "Asisten Noor", reader: "Pembaca Al-Quran", about: "Tentang Situs", install: "Instal Aplikasi", dedication: "Ya Allah, jadikan situs ini sedekah jariyah bagi kami, orang tua, keluarga, dan orang-orang tercinta yang telah wafat. Ampuni dan rahmati mereka serta bantulah kami melayani agama-Mu.", charity: "Al-Quran Al-Majeed — sedekah jariyah; ingatlah kami dalam doa Anda", linksLabel: "Tautan footer", logoAlt: "Logo kanal Al-Quran Suci dan Tilawahnya" },
    live: { primary: "Langsung - Kanal Al-Quran Suci dari Makkah", backup: "Langsung - Kanal Al-Quran Suci (cadangan)", title: "Siaran Langsung", subtitle: "Kanal Al-Quran Suci dan Sunnah Nabi", videoError: "Siaran langsung gagal dimuat. Coba kanal cadangan.", loading: "Memuat siaran...", connected: "Terhubung", quality: "Kualitas koneksi: Sangat baik", available: "Kanal Tersedia", radioPlayer: "Pemutar Radio Langsung", radioSubtitle: "Dengarkan radio Al-Quran dan program Islam", radioTitle: "Radio Al-Quran Suci", radioTagline: "Dengarkan Al-Quran Suci secara langsung", favorite: "Tambah ke favorit", share: "Bagikan radio", noStations: "Tidak ada stasiun radio", connecting: "Menghubungkan...", onAir: "● Langsung", ready: "Siap diputar", choose: "Pilih radio", radioError: "Radio ini tidak dapat diputar. Coba radio lain.", previous: "Radio sebelumnya", next: "Radio berikutnya", pause: "Jeda", play: "Putar", unmute: "Aktifkan suara", mute: "Bisukan", volume: "Volume", channelsLabel: "Kanal siaran langsung" },
  },
  it: {
    footer: { channelTitle: "Il Sacro Corano e le sue recitazioni", channelDesc: "Segui il canale per le recitazioni del Corano e nuovi video di fede.", visitChannel: "Visita il canale su YouTube", siteTitle: "Al-Quran Al-Majeed", siteDesc: "Un Corano digitale gratuito per leggere, ascoltare recitazioni e sfogliare facilmente le pagine del Mushaf su ogni dispositivo.", siteMission: "Chiediamo ad Allah di rendere utile quest’opera e ricompensare chi legge, ascolta e diffonde il bene.", quranBasics: "Fondamenti del Corano", siteServices: "Servizi del sito", quranHome: "Il Sacro Corano", surahs: "Sure del Corano", verseSearch: "Cerca versetti", quranPages: "Pagine del Corano", recitations: "Recitazioni del Corano", mushafLibrary: "Biblioteca dei Mushaf", live: "Trasmissione in diretta", calendar: "Calendario islamico", noor: "Assistente Noor", reader: "Lettore del Corano", about: "Informazioni sul sito", install: "Installa l’app", dedication: "O Allah, rendi questo sito una carità continua per noi, i nostri genitori, le nostre famiglie e i nostri defunti. Perdonali, abbi misericordia di loro e aiutaci a servire la Tua religione.", charity: "Al-Quran Al-Majeed — una carità continua; ricordaci nelle tue preghiere", linksLabel: "Link del piè di pagina", logoAlt: "Logo del canale Il Sacro Corano e le sue recitazioni" },
    live: { primary: "In diretta - Canale del Sacro Corano dalla Mecca", backup: "In diretta - Canale del Sacro Corano (riserva)", title: "Trasmissione in diretta", subtitle: "Canali del Sacro Corano e della Sunna profetica", videoError: "Impossibile caricare la diretta. Prova il canale di riserva.", loading: "Caricamento della diretta...", connected: "Connesso", quality: "Qualità connessione: Eccellente", available: "Canali disponibili", radioPlayer: "Lettore radio in diretta", radioSubtitle: "Ascolta le radio del Corano e i programmi islamici", radioTitle: "Radio del Sacro Corano", radioTagline: "Ascolta il Sacro Corano in diretta", favorite: "Aggiungi ai preferiti", share: "Condividi radio", noStations: "Nessuna radio disponibile", connecting: "Connessione...", onAir: "● In diretta", ready: "Pronto per la riproduzione", choose: "Scegli una radio", radioError: "Impossibile riprodurre questa radio. Provane un’altra.", previous: "Radio precedente", next: "Radio successiva", pause: "Pausa", play: "Riproduci", unmute: "Attiva audio", mute: "Disattiva audio", volume: "Volume", channelsLabel: "Canali di trasmissione in diretta" },
  },
  ja: {
    footer: { channelTitle: "聖クルアーンとその朗誦", channelDesc: "クルアーン朗誦と新しい信仰動画を見るためにチャンネルをフォローしてください。", visitChannel: "YouTubeでチャンネルを見る", siteTitle: "アル＝クルアーン・アル＝マジード", siteDesc: "あらゆる端末でクルアーンを読み、朗誦を聴き、ムスハフのページを簡単に閲覧できる無料デジタルクルアーンです。", siteMission: "この活動が有益となり、読み、聴き、善を広めるすべての人に報いがあるようアッラーに祈ります。", quranBasics: "クルアーンの基本", siteServices: "サイトサービス", quranHome: "聖クルアーン", surahs: "クルアーンのスーラ", verseSearch: "節を検索", quranPages: "クルアーンのページ", recitations: "クルアーン朗誦", mushafLibrary: "ムスハフ図書館", live: "ライブ配信", calendar: "イスラム暦", noor: "Noorアシスタント", reader: "クルアーンリーダー", about: "サイトについて", install: "アプリをインストール", dedication: "アッラーよ、このサイトを私たち、両親、家族、亡き愛する人々のための継続的な慈善としてください。彼らを赦し慈しみ、あなたの宗教に奉仕できるようお助けください。", charity: "アル＝クルアーン・アル＝マジード — 継続的な慈善。祈りの中で私たちを覚えてください", linksLabel: "フッターリンク", logoAlt: "聖クルアーンとその朗誦チャンネルのロゴ" },
    live: { primary: "ライブ - メッカ発 聖クルアーンチャンネル", backup: "ライブ - 聖クルアーンチャンネル（予備）", title: "ライブ配信", subtitle: "聖クルアーンと預言者のスンナのチャンネル", videoError: "ライブ配信を読み込めませんでした。予備チャンネルをお試しください。", loading: "配信を読み込み中...", connected: "接続済み", quality: "接続品質：優良", available: "利用可能なチャンネル", radioPlayer: "ライブ・ラジオプレーヤー", radioSubtitle: "クルアーンラジオとイスラム番組を聴く", radioTitle: "聖クルアーンラジオ", radioTagline: "聖クルアーンをライブで聴く", favorite: "お気に入りに追加", share: "ラジオを共有", noStations: "利用可能なラジオ局がありません", connecting: "接続中...", onAir: "● ライブ", ready: "再生準備完了", choose: "ラジオ局を選択", radioError: "このラジオを再生できません。別の局をお試しください。", previous: "前の局", next: "次の局", pause: "一時停止", play: "再生", unmute: "音声をオン", mute: "ミュート", volume: "音量", channelsLabel: "ライブ配信チャンネル" },
  },
  ko: {
    footer: { channelTitle: "성스러운 꾸란과 낭송", channelDesc: "꾸란 낭송과 새로운 신앙 영상을 위해 채널을 팔로우하세요.", visitChannel: "YouTube에서 채널 보기", siteTitle: "알꾸란 알마지드", siteDesc: "모든 기기에서 꾸란을 읽고 낭송을 들으며 무스하프 페이지를 쉽게 탐색할 수 있는 무료 디지털 꾸란입니다.", siteMission: "이 작업이 유익하고 읽고 듣고 선을 전하는 모든 이에게 보상이 되기를 알라께 기도합니다.", quranBasics: "꾸란 기초", siteServices: "사이트 서비스", quranHome: "성스러운 꾸란", surahs: "꾸란 수라", verseSearch: "절 검색", quranPages: "꾸란 페이지", recitations: "꾸란 낭송", mushafLibrary: "무스하프 도서관", live: "라이브 방송", calendar: "이슬람 달력", noor: "Noor 도우미", reader: "꾸란 리더", about: "사이트 소개", install: "앱 설치", dedication: "알라여, 이 사이트를 우리와 부모님, 가족, 세상을 떠난 이들을 위한 지속적인 자선으로 삼아 주소서. 그들을 용서하고 자비를 베푸시며 저희가 당신의 종교를 섬기도록 도와주소서.", charity: "알꾸란 알마지드 — 지속적인 자선; 기도 속에서 저희를 기억해 주세요", linksLabel: "푸터 링크", logoAlt: "성스러운 꾸란과 낭송 채널 로고" },
    live: { primary: "라이브 - 메카 성스러운 꾸란 채널", backup: "라이브 - 성스러운 꾸란 채널(예비)", title: "라이브 방송", subtitle: "성스러운 꾸란과 예언자 순나 채널", videoError: "라이브 방송을 불러올 수 없습니다. 예비 채널을 이용해 보세요.", loading: "방송 로딩 중...", connected: "연결됨", quality: "연결 품질: 매우 좋음", available: "이용 가능한 채널", radioPlayer: "라이브 라디오 플레이어", radioSubtitle: "꾸란 라디오와 이슬람 프로그램을 들어보세요", radioTitle: "성스러운 꾸란 라디오", radioTagline: "성스러운 꾸란을 라이브로 듣기", favorite: "즐겨찾기에 추가", share: "라디오 공유", noStations: "이용 가능한 라디오가 없습니다", connecting: "연결 중...", onAir: "● 라이브", ready: "재생 준비 완료", choose: "라디오 선택", radioError: "이 라디오를 재생할 수 없습니다. 다른 방송을 이용해 보세요.", previous: "이전 라디오", next: "다음 라디오", pause: "일시정지", play: "재생", unmute: "소리 켜기", mute: "음소거", volume: "볼륨", channelsLabel: "라이브 방송 채널" },
  },
  pt: {
    footer: { channelTitle: "O Sagrado Alcorão e suas recitações", channelDesc: "Siga o canal para recitações do Alcorão e novos vídeos de fé.", visitChannel: "Visitar o canal no YouTube", siteTitle: "Al-Quran Al-Majeed", siteDesc: "Um Alcorão digital gratuito para ler, ouvir recitações e navegar facilmente pelas páginas do Mushaf em qualquer dispositivo.", siteMission: "Pedimos a Allah que torne este trabalho benéfico e recompense todos que leem, ouvem e difundem o bem.", quranBasics: "Fundamentos do Alcorão", siteServices: "Serviços do site", quranHome: "O Sagrado Alcorão", surahs: "Suratas do Alcorão", verseSearch: "Pesquisar versículos", quranPages: "Páginas do Alcorão", recitations: "Recitações do Alcorão", mushafLibrary: "Biblioteca de Mushaf", live: "Transmissão ao vivo", calendar: "Calendário islâmico", noor: "Assistente Noor", reader: "Leitor do Alcorão", about: "Sobre o site", install: "Instalar o aplicativo", dedication: "Ó Allah, faz deste site uma caridade contínua para nós, nossos pais, famílias e entes queridos falecidos. Perdoa-os, tem misericórdia deles e ajuda-nos a servir a Tua religião.", charity: "Al-Quran Al-Majeed — uma caridade contínua; lembre-se de nós em suas orações", linksLabel: "Links do rodapé", logoAlt: "Logotipo do canal O Sagrado Alcorão e suas recitações" },
    live: { primary: "Ao vivo - Canal do Sagrado Alcorão de Meca", backup: "Ao vivo - Canal do Sagrado Alcorão (reserva)", title: "Transmissão ao vivo", subtitle: "Canais do Sagrado Alcorão e da Sunna profética", videoError: "Não foi possível carregar a transmissão. Tente o canal reserva.", loading: "Carregando transmissão...", connected: "Conectado", quality: "Qualidade da conexão: Excelente", available: "Canais disponíveis", radioPlayer: "Reprodutor de rádio ao vivo", radioSubtitle: "Ouça rádios do Alcorão e programas islâmicos", radioTitle: "Rádio do Sagrado Alcorão", radioTagline: "Ouça o Sagrado Alcorão ao vivo", favorite: "Adicionar aos favoritos", share: "Compartilhar rádio", noStations: "Nenhuma rádio disponível", connecting: "Conectando...", onAir: "● Ao vivo", ready: "Pronto para reproduzir", choose: "Escolher uma rádio", radioError: "Não foi possível reproduzir esta rádio. Tente outra.", previous: "Rádio anterior", next: "Próxima rádio", pause: "Pausar", play: "Reproduzir", unmute: "Ativar som", mute: "Silenciar", volume: "Volume", channelsLabel: "Canais de transmissão ao vivo" },
  },
  ru: {
    footer: { channelTitle: "Священный Коран и его чтения", channelDesc: "Подпишитесь на канал, чтобы смотреть чтения Корана и новые духовные видео.", visitChannel: "Посетить канал на YouTube", siteTitle: "Аль-Куран Аль-Маджид", siteDesc: "Бесплатный цифровой Коран для чтения, прослушивания и удобного просмотра страниц Мусхафа на любом устройстве.", siteMission: "Просим Аллаха сделать этот труд полезным и вознаградить каждого, кто читает, слушает и распространяет добро.", quranBasics: "Основы Корана", siteServices: "Сервисы сайта", quranHome: "Священный Коран", surahs: "Суры Корана", verseSearch: "Поиск аятов", quranPages: "Страницы Корана", recitations: "Чтения Корана", mushafLibrary: "Библиотека Мусхафов", live: "Прямая трансляция", calendar: "Исламский календарь", noor: "Помощник Нур", reader: "Чтение Корана", about: "О сайте", install: "Установить приложение", dedication: "О Аллах, сделай этот сайт непрерывной милостыней для нас, наших родителей, семей и ушедших близких. Прости их, помилуй и помоги нам служить Твоей религии.", charity: "Аль-Куран Аль-Маджид — непрерывная милостыня; помните нас в своих молитвах", linksLabel: "Ссылки в подвале", logoAlt: "Логотип канала Священный Коран и его чтения" },
    live: { primary: "Прямой эфир - канал Священного Корана из Мекки", backup: "Прямой эфир - канал Священного Корана (резерв)", title: "Прямая трансляция", subtitle: "Каналы Священного Корана и пророческой Сунны", videoError: "Не удалось загрузить трансляцию. Попробуйте резервный канал.", loading: "Загрузка трансляции...", connected: "Подключено", quality: "Качество соединения: Отличное", available: "Доступные каналы", radioPlayer: "Плеер прямого радио", radioSubtitle: "Слушайте радио Корана и исламские программы", radioTitle: "Радио Священного Корана", radioTagline: "Слушайте Священный Коран в прямом эфире", favorite: "Добавить в избранное", share: "Поделиться радио", noStations: "Нет доступных радиостанций", connecting: "Подключение...", onAir: "● В эфире", ready: "Готово к воспроизведению", choose: "Выберите радиостанцию", radioError: "Не удалось воспроизвести эту станцию. Попробуйте другую.", previous: "Предыдущая станция", next: "Следующая станция", pause: "Пауза", play: "Воспроизвести", unmute: "Включить звук", mute: "Выключить звук", volume: "Громкость", channelsLabel: "Каналы прямой трансляции" },
  },
  tr: {
    footer: { channelTitle: "Kur’an-ı Kerim ve Tilavetleri", channelDesc: "Kur’an tilavetleri ve yeni iman videoları için kanalı takip edin.", visitChannel: "YouTube kanalını ziyaret et", siteTitle: "El-Kur’an El-Mecid", siteDesc: "Her cihazda Kur’an okumak, tilavet dinlemek ve Mushaf sayfalarını kolayca incelemek için ücretsiz dijital Kur’an.", siteMission: "Allah’tan bu çalışmayı faydalı kılmasını ve okuyup dinleyen, iyiliği yayan herkese sevap yazmasını dileriz.", quranBasics: "Kur’an Esasları", siteServices: "Site Hizmetleri", quranHome: "Kur’an-ı Kerim", surahs: "Kur’an Sureleri", verseSearch: "Ayetlerde Ara", quranPages: "Kur’an Sayfaları", recitations: "Kur’an Tilavetleri", mushafLibrary: "Mushaf Kütüphanesi", live: "Canlı Yayın", calendar: "İslami Takvim", noor: "Nur Asistanı", reader: "Kur’an Okuyucu", about: "Site Hakkında", install: "Uygulamayı Yükle", dedication: "Allah’ım, bu siteyi bize, anne babamıza, ailelerimize ve vefat edenlerimize sadaka-i cariye eyle. Onları bağışla, rahmet et ve dinine hizmette bize yardım et.", charity: "El-Kur’an El-Mecid — sadaka-i cariye; dualarınızda bizi unutmayın", linksLabel: "Alt bilgi bağlantıları", logoAlt: "Kur’an-ı Kerim ve Tilavetleri kanal logosu" },
    live: { primary: "Canlı - Mekke’den Kur’an-ı Kerim Kanalı", backup: "Canlı - Kur’an-ı Kerim Kanalı (yedek)", title: "Canlı Yayın", subtitle: "Kur’an-ı Kerim ve Peygamber Sünneti kanalları", videoError: "Canlı yayın yüklenemedi. Yedek kanalı deneyin.", loading: "Yayın yükleniyor...", connected: "Bağlandı", quality: "Bağlantı kalitesi: Mükemmel", available: "Mevcut Kanallar", radioPlayer: "Canlı Radyo Oynatıcısı", radioSubtitle: "Kur’an radyolarını ve İslami programları dinleyin", radioTitle: "Kur’an-ı Kerim Radyosu", radioTagline: "Kur’an-ı Kerim’i canlı dinleyin", favorite: "Favorilere ekle", share: "Radyoyu paylaş", noStations: "Kullanılabilir radyo yok", connecting: "Bağlanıyor...", onAir: "● Canlı", ready: "Oynatmaya hazır", choose: "Radyo seç", radioError: "Bu radyo oynatılamadı. Başka bir radyo deneyin.", previous: "Önceki radyo", next: "Sonraki radyo", pause: "Duraklat", play: "Oynat", unmute: "Sesi aç", mute: "Sessize al", volume: "Ses düzeyi", channelsLabel: "Canlı yayın kanalları" },
  },
  ur: {
    footer: { channelTitle: "قرآنِ کریم اور اس کی تلاوتیں", channelDesc: "قرآن کی تلاوتیں اور نئی ایمانی ویڈیوز دیکھنے کے لیے چینل کو فالو کریں۔", visitChannel: "YouTube پر چینل دیکھیں", siteTitle: "القرآن المجید", siteDesc: "ہر آلے پر قرآن پڑھنے، تلاوت سننے اور مصحف کے صفحات آسانی سے دیکھنے کے لیے مفت ڈیجیٹل قرآن۔", siteMission: "ہم اللہ سے دعا کرتے ہیں کہ وہ اس کام کو نفع بخش بنائے اور پڑھنے، سننے اور بھلائی پھیلانے والوں کو اجر دے۔", quranBasics: "قرآنی بنیادیات", siteServices: "سائٹ کی خدمات", quranHome: "قرآنِ کریم", surahs: "قرآنی سورتیں", verseSearch: "آیات تلاش کریں", quranPages: "قرآن کے صفحات", recitations: "قرآنی تلاوتیں", mushafLibrary: "مصحف لائبریری", live: "براہِ راست نشریات", calendar: "اسلامی تقویم", noor: "نور معاون", reader: "قرآن ریڈر", about: "سائٹ کے بارے میں", install: "ایپ انسٹال کریں", dedication: "اے اللہ، اس سائٹ کو ہمارے، ہمارے والدین، خاندانوں اور مرحوم عزیزوں کے لیے صدقہ جاریہ بنا۔ انہیں بخش دے، ان پر رحم فرما اور اپنے دین کی خدمت میں ہماری مدد فرما۔", charity: "القرآن المجید — صدقہ جاریہ؛ اپنی دعاؤں میں ہمیں یاد رکھیں", linksLabel: "فوٹر روابط", logoAlt: "قرآنِ کریم اور اس کی تلاوتیں چینل کا لوگو" },
    live: { primary: "براہِ راست - مکہ سے قرآنِ کریم چینل", backup: "براہِ راست - قرآنِ کریم چینل (متبادل)", title: "براہِ راست نشریات", subtitle: "قرآنِ کریم اور سنتِ نبوی کے چینلز", videoError: "براہِ راست نشریات لوڈ نہیں ہو سکی۔ متبادل چینل آزمائیں۔", loading: "نشریات لوڈ ہو رہی ہے...", connected: "منسلک", quality: "کنکشن کا معیار: بہترین", available: "دستیاب چینلز", radioPlayer: "براہِ راست ریڈیو پلیئر", radioSubtitle: "قرآن ریڈیو اور اسلامی پروگرام سنیں", radioTitle: "قرآنِ کریم ریڈیو", radioTagline: "قرآنِ کریم براہِ راست سنیں", favorite: "پسندیدہ میں شامل کریں", share: "ریڈیو شیئر کریں", noStations: "کوئی ریڈیو دستیاب نہیں", connecting: "رابطہ ہو رہا ہے...", onAir: "● براہِ راست", ready: "چلانے کے لیے تیار", choose: "ریڈیو منتخب کریں", radioError: "یہ ریڈیو نہیں چل سکا۔ دوسرا ریڈیو آزمائیں۔", previous: "پچھلا ریڈیو", next: "اگلا ریڈیو", pause: "وقفہ", play: "چلائیں", unmute: "آواز چلائیں", mute: "آواز بند کریں", volume: "آواز کی سطح", channelsLabel: "براہِ راست نشریاتی چینلز" },
  },
  zh: {
    footer: { channelTitle: "神圣古兰经及其诵读", channelDesc: "关注频道，观看古兰经诵读和新的信仰视频。", visitChannel: "在 YouTube 上访问频道", siteTitle: "尊贵的古兰经", siteDesc: "免费的数字古兰经，可在任何设备上阅读、聆听诵读并轻松浏览穆斯哈夫页面。", siteMission: "我们祈求安拉使这项工作有益，并回赐每一位阅读、聆听和传播善行的人。", quranBasics: "古兰经基础", siteServices: "网站服务", quranHome: "神圣古兰经", surahs: "古兰经章节", verseSearch: "搜索经文", quranPages: "古兰经页面", recitations: "古兰经诵读", mushafLibrary: "穆斯哈夫图书馆", live: "直播", calendar: "伊斯兰历", noor: "Noor 助手", reader: "古兰经阅读器", about: "关于网站", install: "安装应用", dedication: "安拉啊，请使本网站成为我们、父母、家人和已故亲人的持续善功。求你宽恕并怜悯他们，帮助我们服务你的宗教。", charity: "尊贵的古兰经 — 持续的善功；请在祈祷中记念我们", linksLabel: "页脚链接", logoAlt: "神圣古兰经及其诵读频道标志" },
    live: { primary: "直播 - 来自麦加的神圣古兰经频道", backup: "直播 - 神圣古兰经频道（备用）", title: "直播", subtitle: "神圣古兰经和先知圣行频道", videoError: "无法加载直播，请尝试备用频道。", loading: "正在加载直播...", connected: "已连接", quality: "连接质量：优秀", available: "可用频道", radioPlayer: "直播电台播放器", radioSubtitle: "收听古兰经电台和伊斯兰节目", radioTitle: "神圣古兰经电台", radioTagline: "在线收听神圣古兰经", favorite: "添加到收藏", share: "分享电台", noStations: "没有可用电台", connecting: "正在连接...", onAir: "● 直播", ready: "准备播放", choose: "选择电台", radioError: "无法播放此电台，请尝试其他电台。", previous: "上一个电台", next: "下一个电台", pause: "暂停", play: "播放", unmute: "开启声音", mute: "静音", volume: "音量", channelsLabel: "直播频道" },
  },
} as const;

export const liveSunnahChannelTranslations = {
  ar: "بث مباشر - قناة السنة النبوية من المدينة المنورة",
  en: "Live - Prophetic Sunnah Channel from Madinah",
  de: "Live – Kanal der prophetischen Sunna aus Medina",
  es: "En vivo - Canal de la Sunna profética desde Medina",
  fr: "En direct - Chaîne de la Sunna prophétique depuis Médine",
  hi: "लाइव - मदीना से पैग़ंबरी सुन्नत चैनल",
  id: "Langsung - Kanal Sunnah Nabi dari Madinah",
  it: "In diretta - Canale della Sunna profetica da Medina",
  ja: "ライブ - メディナ発 預言者のスンナチャンネル",
  ko: "라이브 - 메디나 예언자 순나 채널",
  pt: "Ao vivo - Canal da Sunna profética de Medina",
  ru: "Прямой эфир - канал пророческой Сунны из Медины",
  tr: "Canlı - Medine’den Peygamber Sünneti Kanalı",
  ur: "براہِ راست - مدینہ سے سنتِ نبوی چینل",
  zh: "直播 - 来自麦地那的先知圣行频道",
} as const;

export const liveSports1ChannelTranslations = {
  ar: "بث مباشر - قناة الرياضية 1",
  en: "Live - KSA Sports 1",
  de: "Live – KSA Sports 1",
  es: "En vivo - KSA Sports 1",
  fr: "En direct - KSA Sports 1",
  hi: "लाइव - केएसए स्पोर्ट्स 1",
  id: "Langsung - KSA Sports 1",
  it: "In diretta - KSA Sports 1",
  ja: "ライブ - KSAスポーツ1",
  ko: "라이브 - KSA 스포츠 1",
  pt: "Ao vivo - KSA Sports 1",
  ru: "Прямой эфир - KSA Sports 1",
  tr: "Canlı - KSA Sports 1",
  ur: "براہِ راست - کے ایس اے اسپورٹس 1",
  zh: "直播 - KSA体育1台",
} as const;

export const liveSaudiChannelTranslations = {
  ar: "بث مباشر - قناة السعودية",
  en: "Live - Saudi TV",
  de: "Live – Saudi TV",
  es: "En vivo - Saudi TV",
  fr: "En direct - Saudi TV",
  hi: "लाइव - सऊदी टीवी",
  id: "Langsung - Saudi TV",
  it: "In diretta - Saudi TV",
  ja: "ライブ - サウジTV",
  ko: "라이브 - 사우디 TV",
  pt: "Ao vivo - Saudi TV",
  ru: "Прямой эфир - Saudi TV",
  tr: "Canlı - Saudi TV",
  ur: "براہِ راست - سعودی ٹی وی",
  zh: "直播 - 沙特电视台",
} as const;
